version: 1
services:
  - name: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    env:
      - key: FLASK_APP
        value: main.py
      - key: PORT
        value: 8080
